version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - mysqldb
      - redis

  # postgres:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   ports: 
  #     - '5432:5432'
  #   volumes:
  #     - docker-nest-postgres:/var/lib/postgresql/data

  mysqldb:
    image: mysql:8
    command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  db:
  redis:
    driver: local
