name: Deploy to Amazon ECS
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t marcoscamargo7/credenciamento_api .
      - name: Push image docker
        run: docker push marcoscamargo7/credenciamento_api

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull marcoscamargo7/credenciamento_api:latest
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name deploy_credenciamento_api marcoscamargo7/credenciamento_api
