name: Advanced deploy
on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
      - id: deploy
        name: Deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v0.5.8
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws_default_region: us-east-1
          domain_name: bitovi.com
          sub_domain: app
          tf_state_bucket: my-terraform-state-bucket
          dot_env: ${{ secrets.DOT_ENV }}
          ghv_env: ${{ vars.VARS }}
          app_port: 3000
          additional_tags: '{"key1": "value1","key2": "value2"}'
